#!/bin/bash
#=== ---- ==== ---- ==== ---- ==== ---- ==== ---- ==== ---- ==== ---- ==== ----
#	bash functions
# 	created by: Arlo Gittings
# 	created on
# 	last modified: 2021-07-14
# 	descriptions:
# 		Stuff that I find useful in the shell, are a bit more complex than
#       an alias, but not quite needing it's own script, yet. Some should 
#		probably be a script, but they still fit in here.
#=== ---- ==== ---- ==== ---- ==== ---- ==== ---- ==== ---- ==== ---- ==== ----

function bup(){
	# backup before modding
	
	if [ -e $1 ]; then
		cp  $1 $1.`dtstamp`
	else
		echo "${1} does not exist"
	fi
}

function gitacp(){
#== --- === --- === --- === --- === --- === --- === --- === --- === --- === --- 
#   add, validate status, commit and push a git repo in one go
#   
#   usage:
#       gitacp <"Commit reasoning goes here">
#== --- === --- === --- === --- === --- === --- === --- === --- === --- === --- 
    gitacp_opt=''  
    IFS='/' read -r -a gitacp_r_b <<< `git status | grep 'Your branch' | cut -d\' -f2`

    if [ "${*}" ]; then
        gitacp_opt="-m \"$*\""
    fi

    git add *
    git status

    echo "Shall we dance? (y/N)"
    read gitacp_cont
    if [[ ${gitacp_cont} == "y" || ${gitacp_cont} == "Y" ]]; then
        git commit ${gitacp_opt}
        git push ${gitacp_r_b[0]} ${gitacp_r_b[1]}
    else 
        echo 'Aborting. . .'
    fi

    unset gitacp_opt gitacp_r_b gitacp_cont
}
